services:
  - type: web
    name: fullstackopen-cicd
    runtime: node
    rootDir: fs-pokedex-main
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start-prod
    envVars:
      - key: NODE_VERSION
        value: "20"
